เปลี่ยนโลโก้ในNavbar
grindarius/reeba pull request #114
Opened 2022-01-06 13:32 UTC by PhattharapornC

## ✅ DoD / งานที่ทำ

- [x] All work is complete / ทุกอย่างเรียบร้อยดี
- [x] Issues linked: Resolves #108 

## 📝 Summary / สรุปผล

- เปลี่ยนโลโก้ในNavbar ปรับขนาดโลโก้และให้โลโก้ลงมาอยู่ตรงกลาง

## 💉 Testing / ทดสอบ

- รัน npm dev:frontend ได้ปกติ

## 🛑 Problems / ปัญหา

- เมื่อ Pull origin มีติดเหลืองที่ apply และติดแดงที่ } แต่สามารถรันได้ปกติ

## 💡 More ideas / ไอเดีย

ไม่มี

## 📸 Screenshots / ภาพถ่าย

![image](https://user-images.githubusercontent.com/95341163/148389758-0b16a94b-6196-42ca-b38d-2fc3cb9a1155.png)

2022-01-06 13:55 UTC, grindarius requested changes

2022-01-06 13:55 UTC, grindarius commented on packages/frontend/src/App.vue
> +          <img src="@/assets/reeba-logo-2.png" alt="Reeba logo" width="25"  class="ml-2 cursor-pointer">
รูปมันขนาดเท่าไหร่อะ มันน่าจะใหญ่กว่าแถบ navbar อยู่ เค้าคิดว่า โลโก้มันน่าจะใหญ่กว่านี้อีกหน่อย ความรู้สึกว่ามันเล็กไปนิดนึง

2022-01-06 14:13 UTC, grindarius commented on packages/frontend/src/App.vue
> +    <div class="big-navbar mt-2.5">
ห้ามกำหนด margin หรือ padding ตรงนี้โดยเด็ดขาด มันทำให้ปุ่มทางขวาเข ไม่ขนานกัน

2022-01-06 14:25 UTC, PhattharapornC commented on packages/frontend/src/App.vue
> +    <div class="big-navbar mt-2.5">
แล้วสามารถกำหนดในclass logo, searchbar, buttonได้มั้ยคือถ้าไม่กำหนดมันจะลอยไปติดข้างบนหมดเลย

2022-01-06 14:50 UTC, grindarius commented on packages/frontend/src/App.vue
> +    <div class="big-navbar mt-2.5">
*ไม่ได้*

มีทางนึงก็คือใช้ flex items-center มันจะลอยอยู่ตรงกลาง หรือไม่ก็กำหนดความกว้างรูปให้เท่ากับขอบของ navbar เลย

2022-01-07 06:44 UTC, grindarius approved these changes

2022-01-07 06:44 UTC, merged