verified user tick
grindarius/reeba pull request #210
Opened 2022-02-19 14:36 UTC by pasinchanla

## ✅ DoD / งานที่ทำ

- [x] All work is complete / ทุกอย่างเรียบร้อยดี
- [x] Issues linked: Resolves #143 

## 📝 Summary / สรุปผล

เพิ่มเครื่องหมาย verified ข้างชื่อในหน้า users กับ accounts
***inner screen ให้อาจารย์แจดูเว็บแล้วเขาบอกว่าความกว้างขนาดเดิมดีอยู่แล้ว ไม่จำเป็นต้องเปลี่ยนเลยขอไม่เปลี่ยนดีกว่า

## 💉 Testing / ทดสอบ
- [x] can you run `pnpm test` without any errors? / รัน `pnpm test` แล้วไม่มีเออเร่อ
- [x] can you run `pnpm build -r` without any errors? / รัน `pnpm build -r` แล้วไม่มีเออเร่อ
- more tests / การทดสอบเพิ่มเติม

## 🛑 Problems / ปัญหา

- ปุ่ม follow เพิ่ม hover ให้ แต่ยังไม่มีการกดแล้วข้อความเปลี่ยนเป็น unfollow

## 💡 More ideas / ไอเดีย

- ควรเพิ่ม event creator ในหน้า event เพื่อให้คนทั่วไปสามารถกด follow ได้

## 📸 Screenshots / ภาพถ่าย
![image](https://user-images.githubusercontent.com/69805712/154805235-bfa242cd-1ed4-4f5a-9df5-9a5ebcbd88a6.png)
![image](https://user-images.githubusercontent.com/69805712/154805240-f29f09a2-2d59-496b-ae74-792a0e9016e9.png)
![image](https://user-images.githubusercontent.com/69805712/154805246-652cfe47-07a2-4a83-b10e-2376e4b93456.png)

2022-02-19 14:44 UTC, LzzAa35 approved these changes
Nice

2022-02-19 14:55 UTC, grindarius requested changes

2022-02-19 14:55 UTC, grindarius commented on packages/frontend/src/views/users.vue
> +  @apply flex flex-row justify-center gap-1 text-center  text-white; }
ปีกกาปัดได้ไง

2022-02-19 15:15 UTC, grindarius approved these changes
looks good to me

2022-02-19 17:11 UTC, grindarius requested changes
อย่าลืม pnpm lint:css

2022-02-20 13:38 UTC, grindarius approved these changes

2022-02-20 13:40 UTC, merged