Create Not found page and button.
grindarius/reeba pull request #212
Opened 2022-02-20 18:55 UTC by Sopaphorn

Not found page have image 404. Button have 2 button (go home and connect again).

## ✅ DoD / งานที่ทำ

- [x] All work is complete / ทุกอย่างเรียบร้อยดี
- [x] Issues linked: Resolves #xyz

## 📝 Summary / สรุปผล

- Write a list of changes / เขียนรายละเอียดว่าทำอะไรลงไป
- ออกแบบหน้า Not found และเขียนโค้ดสร้างหน้าเพจขึ้นมา จะมีทั้งรุปภาพ 404 Not Found และมีปุ่มทั้งหมด 2 ปุ่ม คือ ปุ่ม go home กับปุ่ม connect again

## 💉 Testing / ทดสอบ

- [x] can you run `pnpm test` without any errors? / รัน `pnpm test` แล้วไม่มีเออเร่อ
- [x] can you run `pnpm build -r` without any errors? / รัน `pnpm build -r` แล้วไม่มีเออเร่อ
- more tests / การทดสอบเพิ่มเติม

## 🛑 Problems / ปัญหา

- Write any discovered & unresolved problems / เขียนปัญหาที่เกิดขึ้น และปัญหาที่แก้ไม่ได้
- ไม่มี

## 💡 More ideas / ไอเดีย

Write any more ideas you have / ถ้ามีไอเดียใหม่ ๆ
ไม่มี

## 📸 Screenshots / ภาพถ่าย

Put screenshots here! / แปะภาพตรงนี้
![image](https://user-images.githubusercontent.com/82072741/154858459-89d93086-1527-4c19-8a87-3187db6a0342.png)
![image](https://user-images.githubusercontent.com/82072741/154859150-5cec47bd-6fa6-4433-ba39-5b2e4cc5b960.png)

2022-02-20 18:56 UTC, grindarius requested changes
`pnpm lint:css` แล้วยัง

2022-02-20 18:58 UTC, Sopaphorn commented
> 

เรียบร้อยแล้วค่ะ =)

2022-02-20 18:59 UTC, grindarius commented
จะไม่ให้ผ่านจนกว่า @pasinchanla มาอ่าน

2022-02-20 20:31 UTC, grindarius commented
ปุ่นมันทำไมถึงกดแล้วไม่ไปอะ

2022-02-21 01:07 UTC, pasinchanla requested changes

2022-02-21 01:07 UTC, pasinchanla commented on packages/frontend/src/views/not-found.vue
> +            conect again
connect again นี่คือปุ่มไว้ใช้ทำอะไร
P.S. แก้ conect เป็น connect ด้วย

2022-02-21 01:08 UTC, pasinchanla commented on packages/frontend/src/views/not-found.vue
> +            conect again
และก็ปุ่มยังกดไม่ได้ด้วย

2022-02-21 03:24 UTC, LzzAa35 requested changes
- จะใช้แบบเดิมก็ได้นะ `NOT FOUND` เจ๋งดี อันนี้ยังไงก็ได้นะหรือลองใช้คำอื่นๆ เช่น 
`Oops! Page Not Found` หรืออื่นๆ
- อยากให้มีคำอธิบายสั้นๆ ว่า หน้านี้ไม่มีนะ หรือ  ทำไมไม่ลองวิธีนี้แทนล่ะ? แล้วก็เป็นปุ่มเหมือนเดิม
- ปุ่มยังกดไม่ได้

2022-02-21 11:16 UTC, Sopaphorn commented
> ปุ่นมันทำไมถึงกดแล้วไม่ไปอะ

อ่าาา ไม่ได้ลิ้งค์ โอเคค พลาดเอง

2022-02-21 16:01 UTC, Sopaphorn commented
You can press the button and fixed word from "NOT FOUND" to " PAGE NOT FOUND".
![image](https://user-images.githubusercontent.com/82072741/154989784-e4e23b3b-cf76-48d7-87f3-df9a89673057.png)

2022-02-21 16:15 UTC, pasinchanla commented
> You can press the button and fixed word from "NOT FOUND" to " PAGE NOT FOUND". Add a description under 404. ![image](https://user-images.githubusercontent.com/82072741/154989784-e4e23b3b-cf76-48d7-87f3-df9a89673057.png)

![image](https://user-images.githubusercontent.com/69805712/154992042-0cee557a-1649-4ef7-9b9f-9271d0cc8bb0.png)
ทำไม exist มันมีตัวไรแปลก ๆ ตรง s ด้วย
และก็บรรทัดที่สอง ใช้ ...go to home page ...

2022-02-21 16:17 UTC, pasinchanla approved these changes
แก้ตามคอมเม้นที่บอกไปเลย

2022-02-21 16:17 UTC, pasinchanla commented on packages/frontend/src/views/not-found.vue
> +              go home
ใช้ Go Home ตัวใหญ่ดีกว่า

2022-02-21 16:20 UTC, grindarius commented
> > You can press the button and fixed word from "NOT FOUND" to " PAGE NOT FOUND". Add a description under 404. ![image](https://user-images.githubusercontent.com/82072741/154989784-e4e23b3b-cf76-48d7-87f3-df9a89673057.png)
> 
> ![image](https://user-images.githubusercontent.com/69805712/154992042-0cee557a-1649-4ef7-9b9f-9271d0cc8bb0.png)
> ทำไม exist มันมีตัวไรแปลก ๆ ตรง s ด้วย
> และก็บรรทัดที่สอง ใช้ ...go to home page ...

Go to home page

2022-02-21 16:22 UTC, grindarius requested changes
อย่าลืม `pnpm lint:css`

2022-02-21 16:22 UTC, grindarius commented on packages/frontend/src/views/not-found.vue
> +          <router-link to="/" class="buy-button">
buy-button อะไรเนี่ย ซื้ออะไร

2022-02-21 16:22 UTC, grindarius commented on packages/frontend/src/views/not-found.vue
> +        <div class="whitespace-nowrap botton">
botton นี่คืออะไรรึ button รึเปล่า

2022-02-21 16:22 UTC, grindarius commented on packages/frontend/src/views/not-found.vue
> +      <section class="contrainer">
container รึเปล่า

2022-02-21 16:22 UTC, grindarius commented on packages/frontend/src/views/not-found.vue
> +          <!-- <button
ปุ่มนี้ไม่เอาก็ลบออก

2022-02-21 16:24 UTC, Sopaphorn commented on packages/frontend/src/views/not-found.vue
> +          <router-link to="/" class="buy-button">
> buy-button อะไรเนี่ย ซื้ออะไร
ไปดูของแบงค์มา ละก็โป๊ะ ลืมเปลี่ยนชื่อขอโทษครับ

2022-02-21 16:35 UTC, Sopaphorn commented on packages/frontend/src/views/not-found.vue
> +              go home
> ใช้ Go Home ตัวใหญ่ดีกว่า

GO HOME ดีมั้ยอ่ะ คิดว่าไง หรือว่า Go home พอ

2022-02-21 16:42 UTC, Sopaphorn commented
@pasinchanla @grindarius Fixed word, class name and font text.
![image](https://user-images.githubusercontent.com/82072741/154996341-f44a7b13-da7c-4151-8b6a-fa6b8dbf2efb.png)

2022-02-21 16:52 UTC, Sopaphorn commented
Fixed @grindarius @pasinchanla 
![image](https://user-images.githubusercontent.com/82072741/154997545-494d194a-f1b8-4538-a7b4-c62684a180fd.png)

2022-02-21 17:39 UTC, grindarius approved these changes
รูปยังมี padding ข้าง ๆ มากเกินไป ทำให้จัดการกับขนาดได้ยากเมื่อนำ whitespace มาคิด แต่โดยรวมโอเคแล้ว

2022-02-21 17:39 UTC, grindarius commented on packages/frontend/src/views/not-found.vue
> +              go home
เราเลือก Go home ไปแล้ว

2022-02-21 17:40 UTC, grindarius commented
> * จะใช้แบบเดิมก็ได้นะ `NOT FOUND` เจ๋งดี อันนี้ยังไงก็ได้นะหรือลองใช้คำอื่นๆ เช่น
>   `Oops! Page Not Found` หรืออื่นๆ
> * อยากให้มีคำอธิบายสั้นๆ ว่า หน้านี้ไม่มีนะ หรือ  ทำไมไม่ลองวิธีนี้แทนล่ะ? แล้วก็เป็นปุ่มเหมือนเดิม
> * ปุ่มยังกดไม่ได้

เสร็จแล้ว

2022-02-21 17:43 UTC, LzzAa35 approved these changes
Nice

2022-02-21 17:46 UTC, merged