Add new country code
grindarius/reeba pull request #218
Opened 2022-02-22 16:17 UTC by PawinaK

## ✅ DoD / งานที่ทำ

- [x] All work is complete / ทุกอย่างเรียบร้อยดี
- [x] Issues linked: Resolves #169, 
- [x] Issues linked: Resolves #174

## 📝 Summary / สรุปผล

-ทำ footer 
-หน้า register เพิ่มช่อง Phone country number ใส่ชื่อประเทศกับรหัสโทรศัพท์

## 💉 Testing / ทดสอบ

- [x] can you run `pnpm test` without any errors? / รัน `pnpm test` แล้วไม่มีเออเร่อ
- [x] can you run `pnpm build -r` without any errors? / รัน `pnpm build -r` แล้วไม่มีเออเร่อ

## 🛑 Problems / ปัญหา

- หน้า footer หาไอคอนไลน์ไม่ได้ เลยใส่ไอคอมอินบล็อกแทนไปก่อน
- Drop down ไม่ตรง แก้แล้ว
- หน้า footer ไม่ค่อยเข้าใจโค้ด Drop down อันใหม่
- ใส่ธงประเทศยังไม่ได้

## 💡 More ideas / ไอเดีย

คิดว่ายังไม่มี

## 📸 Screenshots / ภาพถ่าย
![Dropdown](https://user-images.githubusercontent.com/95273691/155142152-9dcf1778-281b-42ea-aca7-cfde3f17b0b8.gif)
![footer](https://user-images.githubusercontent.com/95273691/155142380-5a02056c-e68f-4414-aaee-15cb4d8f0047.gif)

2022-02-22 16:35 UTC, grindarius requested changes

2022-02-22 16:35 UTC, grindarius commented on packages/frontend/src/views/register.vue
> +            Already have an account? <a class="font-bold">Sign in</a>
จุดหายไปไหน

2022-02-23 01:50 UTC, pasinchanla approved these changes

2022-02-23 01:50 UTC, pasinchanla commented
ตอนนี้มันยังเป็นช่องให้กรอกอย่างเดียวอยู่เนอะ

ต่อไปที่ต้องคิดคือปกติเวลาพิมพ์เบอร์โทรศัพท์จะมีคน 2 แบบ
1. พิมพ์ 0 ไว้ข้างหน้าด้วย เช่น 095-xxx-xxxx
2. ไม่พิมพ์ 0 เลย เช่น 95-000-0000

คำถามคือเราจะทำยังไงให้เวลาพิมพ์แบบแรกแล้วเว็บเราจะตัด 0 ตัวแรกออก

2022-02-23 04:55 UTC, LzzAa35 approved these changes
Nice
ดูคำแนะนำที่  Pasin ต่อได้เลย

2022-02-23 05:04 UTC, grindarius commented
> ตอนนี้มันยังเป็นช่องให้กรอกอย่างเดียวอยู่เนอะ
> 
> ต่อไปที่ต้องคิดคือปกติเวลาพิมพ์เบอร์โทรศัพท์จะมีคน 2 แบบ
> 
> 1. พิมพ์ 0 ไว้ข้างหน้าด้วย เช่น 095-xxx-xxxx
> 2. ไม่พิมพ์ 0 เลย เช่น 95-000-0000
> 
> คำถามคือเราจะทำยังไงให้เวลาพิมพ์แบบแรกแล้วเว็บเราจะตัด 0 ตัวแรกออก

วิธีที่คิดไว้ตอนนี้คือจะใช้ RegExp เป็นตัวกำหนดว่าให้เขาใส่แต่เลข ก็พอละ เพราะว่าเวลาเราโทรเราก็กดแต่เลข ถ้าระบบเราจะโทรหาเขา เราก็คงจะให้ใส่แต่เลข

https://en.wikipedia.org/wiki/Trunk_prefix

จากลิงค์นี้ ไม่ใช่ทุกประเทศใช้ trunk prefix เป็นเลข 0 เหมือนกัน ดังนั้น คิดว่าเราไม่ควรตัด แต่ปัดภาระนี้ให้กับ user หรือมีคำอธิบายเวลา focus อยู่ที่ตัว input

2022-02-23 05:13 UTC, pasinchanla commented
> > ตอนนี้มันยังเป็นช่องให้กรอกอย่างเดียวอยู่เนอะ
> 
> > 
> 
> > ต่อไปที่ต้องคิดคือปกติเวลาพิมพ์เบอร์โทรศัพท์จะมีคน 2 แบบ
> 
> > 
> 
> > 1. พิมพ์ 0 ไว้ข้างหน้าด้วย เช่น 095-xxx-xxxx
> 
> > 2. ไม่พิมพ์ 0 เลย เช่น 95-000-0000
> 
> > 
> 
> > คำถามคือเราจะทำยังไงให้เวลาพิมพ์แบบแรกแล้วเว็บเราจะตัด 0 ตัวแรกออก
> 
> 
> 
> วิธีที่คิดไว้ตอนนี้คือจะใช้ RegExp เป็นตัวกำหนดว่าให้เขาใส่แต่เลข ก็พอละ เพราะว่าเวลาเราโทรเราก็กดแต่เลข ถ้าระบบเราจะโทรหาเขา เราก็คงจะให้ใส่แต่เลข
> 
> 
> 
> https://en.wikipedia.org/wiki/Trunk_prefix
> 
> 
> 
> จากลิงค์นี้ ไม่ใช่ทุกประเทศใช้ trunk prefix เป็นเลข 0 เหมือนกัน ดังนั้น คิดว่าเราไม่ควรตัด แต่ปัดภาระนี้ให้กับ user หรือมีคำอธิบายเวลา focus อยู่ที่ตัว input

โอเคเลย งั้นก็เหลือแค่เวลา user กรอกเลขเกินก็ให้มีตัวแดงขึ้นก็น่าจะไม่ต้องเพิ่มไรละ

2022-02-24 02:12 UTC, grindarius approved these changes

2022-02-24 02:14 UTC, merged