update hover & disabled color
grindarius/reeba pull request #77
Opened 2021-12-29 14:54 UTC by pasinchanla

## ✅ DoD / งานที่ทำ

- [ x] All work is complete / ทุกอย่างเรียบร้อยดี
- [ x] Issues linked: Resolves #76 

## 📝 Summary / สรุปผล

- เพิ่มสีของ Hover เวลาเอาเมาส์ไปชี้แล้วจะเป็นอีกเฉดสี
- เพิ่มสี Disabled เวลาไม่ต้องการให้ปุ่มนั้นกดได้

## 💉 Testing / ทดสอบ

- เพิ่มปุ่ม Test Button ใน payment เพื่อ testing การใช้สี

## 🛑 Problems / ปัญหา

ไม่มี

## 💡 More ideas / ไอเดีย

ไม่มี

## 📸 Screenshots / ภาพถ่าย
![GIF 12-29-2021 9-42-38 PM](https://user-images.githubusercontent.com/69805712/147674742-5a742dae-2e55-4651-af5d-755fa6fc1fa2.gif)
![image](https://user-images.githubusercontent.com/69805712/147674678-1b572d95-fe63-4eb5-bbf8-4955feb4671e.png)

2021-12-29 17:07 UTC, Sopaphorn requested changes
I think your button color is ok. But if you using hover : bg-amber-400 it will be better.
Before
![image](https://user-images.githubusercontent.com/82072741/147686536-d757121a-478a-41a4-aecd-09ebde33e918.png)
After
![image](https://user-images.githubusercontent.com/82072741/147686553-e05a9c90-1fb3-458b-a12d-6d8cfc90f5d9.png)

2021-12-30 03:04 UTC, grindarius commented
@pasinchanla คิดว่าเราควรมีสี hover และ disabled สำหรับสีเทาด้วยรึเปล่า

2021-12-30 04:57 UTC, grindarius approved these changes
ในด้านของโค้ด ดูดี ให้ผ่านไว้ก่อน

2021-12-30 08:31 UTC, pasinchanla commented
![image](https://user-images.githubusercontent.com/69805712/147734847-f6e32518-7b24-44ec-9af6-30080a7c48d5.png)


> I think your button color is ok. But if you using hover : bg-amber-400 it will be better. Before ![image](https://user-images.githubusercontent.com/82072741/147686536-d757121a-478a-41a4-aecd-09ebde33e918.png) After ![image](https://user-images.githubusercontent.com/82072741/147686553-e05a9c90-1fb3-458b-a12d-6d8cfc90f5d9.png)
![yellow](https://user-images.githubusercontent.com/69805712/147734883-55fa9388-7712-4ec0-9e07-5e179bae4bc1.gif)

2021-12-30 09:32 UTC, LzzAa35 approved these changes
![nice](https://user-images.githubusercontent.com/62424250/147737432-876f5595-84cf-4dd9-a15a-c63753677922.gif)

2021-12-30 10:38 UTC, grindarius approved these changes
code looks good so yeah, waiting on @Sopaphorn

2021-12-31 06:50 UTC, Sopaphorn commented
สำหรับฉันโอเคแล้วนะ แต่จะเพิ่มอะไรอีกก็แล้วแต่พิจารณาของตัวเองและเพื่อนในกลุ่มเลย

2021-12-31 09:15 UTC, Sopaphorn approved these changes

2021-12-31 09:15 UTC, merged